name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 23f3004394@ds.study.iitm.ac.in
        run: echo "Hello, world!"
